const placesclavero = [
    {
        id: 1,
        name: "Altas Cumbres y Pampa de Achala - Mina Clavero",
        desp: "Altas cumbres y pampa de achala: Las Altas cumbres es un paseo que muchos se pierden de disfrutar en el afán de llegar cuanto antes a destino. Para aquellos que saben disfrutar del camino esta obra de ingeniería vial un lugar maravilloso. La Pampa de Achala conforma un ecosistema de altura y regula el caudal de los arroyos y ríos de los valles cordobeses, toda el agua que cae en forma de lluvias, granizos, heladas, nevadas y neblinas, es receptada por el manto vegetal que funciona como una “esponja”  y luego por decantación es alimento de diques y lagunas que permiten desarrollar las diferentes actividades turísticas y económicas de toda la región. Los picos más altos llegan a 2200 metros sobre el nivel del mar.",
        img_1: "../imgs/turisticos/mina-clavero/1/alpinista-.jpg",
        img_2: "../imgs/turisticos/mina-clavero/1/camino-curva.jpg",
        img_3: "../imgs/turisticos/mina-clavero/1/camino-nuevo.jpg",
        location: "https://www.google.com/maps/search/?api=1&query=-31.61628,-64.875376",
    },
    {
        id: 2,
        name: "Puentes Colgantes - Mina Clavero",
        desp: "Puentes colgantes: Un paseo de todo el día que le hará recorrer el corazón de traslasierra y sorprenderse con su naturaleza virgen. Si posee auto todo terreno aventúrese usted mismo a conocer estos puentes de piedra y madera forjados a pico y masa con el entusiasmo de conectar pueblo, de achicar distancias. Si prefiere y fotografiando y despreocuparse de sus amortiguadores contrate una excursión en los sitios de turismo de Mina Clavero y relájese en su asiento.",
        img_1: "../imgs/turisticos/mina-clavero/2/puente-2.jpg",
        img_2: "../imgs/turisticos/mina-clavero/2/puente-col-1.jpg",
        img_3: "../imgs/turisticos/mina-clavero/2/puente-curva.jpg",
        location: "https://www.google.com/maps/search/?api=1&query=-31.562225,-64.709059",
    },
    {
        id: 3,
        name: "Balneario Nido de Aguilas - Mina Clavero",
        desp: "Balneario natural ubicado a solo 1.500 metros del centro de MC. Se puede llegar en auto o caminando, siguiendo los carteles indicadores sobre la calle Urquiza. En este lugar el río Mina Clavero se encajona entre paredones de granito modelados por la erosión del aire y del agua, dando origen a una pileta natural que en algunos sectores supera los 6 metros de profundidad. El sitio es ideal para clavadistas.",
        img_1: "../imgs/turisticos/mina-clavero/3/nido-ae-1.jpg",
        img_2: "../imgs/turisticos/mina-clavero/3/nido-ae-3.jpg",
        img_3: "../imgs/turisticos/mina-clavero/3/nido-de-aguila.jpg",
        location: "https://www.google.com/maps/search/?api=1&query=-31.725022,-64.991487",
    },
    {
        id: 4,
        name: "Balneario La Toma - Mina Clavero",
        desp: "La Toma: Tan sólo a 5 km de la plaza de Mina Clavero, por el camino de los artesanos, del rally mundial, del Cura Brochero. La Toma es una belleza impactante: su olla de piedra y sus toboganes hacen del lugar un parque acuático de la naturaleza. El agua helada señala el río Mina Clavero,  un río de caída, de quebrada, apenas nace ya está en la Toma y pasando a toda velocidad. Ver salir la luna llena desde un yacuzzi natural es la postal de la Toma. Estacionamiento tarifado y bar con proveeduría. Poca sombra. Recomendado hacer el camino siguiendo el cauce del río, usando cómo guía los caños de agua. (2 hs de caminata) .",
        img_1: "../imgs/turisticos/mina-clavero/5/la-toma-pileta.jpg",
        img_2: "../imgs/turisticos/mina-clavero/5/pileton-1.jpg",
        img_3: "../imgs/turisticos/mina-clavero/5/pileton-2.jpg",
        location: "https://www.google.com/maps/search/?api=1&query=-31.714252,-64.96939",
    },
    {
        id: 5,
        name: "Balneario Los Elefantes - Mina Clavero",
        desp: "Sobre el cauce del río de Los Sauces se encuentran Los Elefantes, donde el agua transita la cuenca cerrada, formando rápidos y profundas ollas (sólo para expertos nadadores). Al final de los cajones, donde la cuenca se abre, surge a ambos costados una formación rocosa que se asemeja a la figura de dos elefantes, de ahí su nombre.",
        img_1: "../imgs/turisticos/mina-clavero/6/altas-cumbres-dde-los-elefantes.jpg",
        img_2: "../imgs/turisticos/mina-clavero/6/atardecer.jpg",
        img_3: "../imgs/turisticos/mina-clavero/6/elef-2.jpg",
        location: "https://www.google.com/maps/search/?api=1&query=-31.721801,-65.011011",
    },
    {
        id: 6,
        name: "Nacimiento del Río Mina Clavero - Mina Clavero",
        desp: "Nacimiento del río Mina Clavero: Situada a 30km de Mina Clavero esta espectacular caída de agua de 102 metros representa el poder de la naturaleza en su máxima expresión, la espuma del agua golpeando contra las piedras; el sendero con barrancos, los cóndores planeando y una naturaleza activa hacen del Nacimiento del río Mina Clavero una parada obligatoria para viajantes y turistas que deseen conocer el origen de tantos balnearios bellos. ",
        img_1: "../imgs/turisticos/mina-clavero/7/camino-altas-cumbres-altura-naciemiento.jpg",
        img_2: "../imgs/turisticos/mina-clavero/7/casacada-rio-mina-clavero-2.jpg",
        img_3: "../imgs/turisticos/mina-clavero/7/cascada-algarrobo.jpg",
        location: "https://www.google.com/maps/place/32%C2%B013'02.8%22S+65%C2%B002'54.2%22W/@-32.217441,-65.048378,17z/data=!3m1!4b1!4m4!3m3!8m2!3d-32.217441!4d-65.048378?entry=ttu&g_ep=EgoyMDI1MDQxMy4wIKXMDSoJLDEwMjExNjM5SAFQAw%3D%3D",
    },
    {
        id: 7,
        name: "Playa del rio de los Sauces - Mina Clavero",
        desp: "Los ríos son el gran atractivo de Mina Clavero. El Panaholma y el Mina Clavero dan origen a numerosos balnearios naturales. Aguas abajo, en el límite con Villa Cura Brochero, ambos se unen dando nacimiento al Río de los Sauces; de amplias playas de arena fina que se suceden a lo largo de todo su curso hasta desembocar en el Dique La Viña.",
        img_1: "../imgs/turisticos/mina-clavero/8/cartel-burros.jpg",
        img_2: "../imgs/turisticos/mina-clavero/8/mina-ae-alto.jpg",
        img_3: "../imgs/turisticos/mina-clavero/8/rio-vigua-ae.jpg",
        location: "https://www.google.com/maps/search/?api=1&query=-31.736447,-65.01077",
    },
    {
        id: 8,
        name: "Balneario la Residencia - Mina Clavero",
        desp: "Se encuentra a 900 metros del puente Central de Mina Clavero, al pie del tradicional hotel Residencia Serrana. El río es poco profundo y con playas extensas, ideal para familias y niños.",
        img_1: "../imgs/turisticos/mina-clavero/9/resi-ae-2.jpg",
        img_2: "../imgs/turisticos/mina-clavero/9/resi-ae-3.jpg",
        img_3: "../imgs/turisticos/mina-clavero/9/resi-ae1.jpg",
        location: "https://www.google.com/maps/search/?api=1&query=-31.724981,-64.996443",
    },
    {
        id: 9,
        name: "Playas del centro - Mina Clavero",
        desp: "Sobre la cuenca del río Mina Clavero, entre el puente central y el puente Olmos. La música y las actividades en la arena convierten a estas playas en las preferidas por los jóvenes. Son amplias y de arena fina y a lo largo de toda su extensión hay parrillas, restaurantes, bares y kioskos. En temporada baja es el sitio elegido para la organización de eventos para toda la familia. ",
        img_1: "../imgs/turisticos/mina-clavero/10/balneario-2.jpg",
        img_2: "../imgs/turisticos/mina-clavero/10/central-ae1-.jpg",
        img_3: "../imgs/turisticos/mina-clavero/10/playa-llena-4.jpg",
        location: "https://www.google.com/maps/search/?api=1&query=-31.725114,-65.002858",
    },
    {
        id: 10,
        name: "Balneario Abuela Teresa - Mina Clavero",
        desp: "Extenso balneario en las sierras, en el nacimiento del Río Hondo. Ideal para pasar el día.",
        img_1: "../imgs/turisticos/mina-clavero/11/olla.jpg",
        img_2: "../imgs/turisticos/mina-clavero/11/rio.jpg",
        img_3: "../imgs/turisticos/mina-clavero/11/vado-rio.jpg",
        location: "https://www.google.com/maps/search/?api=1&query=-31.658149,-64.948513",
    },
    {
        id: 11,
        name: "Camino Viejo y Ruta de Los Artesanos - Mina Clavero",
        desp: "Este camino es una oportunidad única de entrar en contacto con los responsables de dos de las más valiosas expresiones del patrimonio cultural de Traslasierra: la cerámica negra y el tejido de telar. El circuito permite conocer a alfareros y tejenderas de la sierra, que abren la puerta de sus hogares/talleres dispuestos a mostrar los secretos de un oficio centenario que mantiene viva la identidad de todo un pueblo. El camino se inicia en el Encuentro de Tejenderos, frente al puesto policial sobre el Camino de las Altas Cumbres. Luego, desde la plaza central de Mina Clavero se debe tomar la calle Jorge R. Recalde y seguir las señales que indican Camino de Los Artesanos. Los talleres pueden visitarse todo el año, durante todo el día.",
        img_1: "../imgs/turisticos/mina-clavero/4/acceso-de-altas-cumbres-al-cno-viejo.jpg",
        img_2: "../imgs/turisticos/mina-clavero/4/camino-curva.jpg",
        img_3: "../imgs/turisticos/mina-clavero/4/curvon.jpg",
        location: "https://www.google.com/maps/search/?api=1&query=-31.682544,-64.978416",
    },
];

export default placesclavero;